from .cifar10 import *
from .cifar100 import *
from .mnist import *
from .svhn import *
from .tinyimagenet import *
from .agnews import *
from .imdb import *
from .sst5 import *
from .dbpedia import *
from .yelp import *